class Task_list:
    def __init__(self,filtered_data, combined_data):
        self.filtered_data = filtered_data
        self.combined_data = combined_data
        
    def list(self):
        return {
                "1on1":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"1on1",
                    "chart_key":"Calculate_1on1_chart",
                },
                "NST":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"NST",
                    "chart_key":"Calculate_NST_chart",
                },
                "TDM実施":{
                    "chart_func":"count_task_chart",
                    "task_name":"TDM実施",
                    "chart_key":"Calculate_TDM_chart",
                    "show_dataframe":True,
                    "chart":True,
                },
                "TPN評価":{
                    "chart_func":"count_task_chart",
                    "task_name":"TPN評価",
                    "chart_key":"Calculate_TPN_chart",
                    "show_dataframe":True,
                    "chart":False,
                },
                "WG活動":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"WG活動",
                    "chart_key":"Calculate_WG_chart",
                },
                "カンファレンス":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"カンファレンス",
                    "chart_key":"Calculate_conference_chart",
                },
                "管理業務":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"管理業務",
                    "to_hours":True,
                    "chart_key":"Manegment_time_chart",
                },
                "業務調整":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"業務調整",
                    "to_hours":True,
                    "chart_key":"Adjustment_work_chart",
                },
                "持参薬を確認":{
                    "chart_func":"count_task_chart",
                    "task_name":"持参薬を確認",
                    "chart_key":"Check_Medication_chart",
                },
                "服薬指導＋指導記録作成":{
                    "chart_func":"count_task_chart",
                    "task_name":"服薬指導＋指導記録作成",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Medication_guidance_and_record_chart",
                },
                "服薬指導":{
                    "chart_func":"count_task_chart",
                    "task_name":"服薬指導",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Medication_guidance_chart",
                },
                "指導記録作成":{
                    "chart_func":"count_task_chart",
                    "task_name":"指導記録作成",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Instruction_record_chart",
                },
                "初回・中間指導情報収集":{
                    "chart_func":"count_task_chart",
                    "task_name":"初回・中間指導情報収集",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Initial_and_interim_guidance_info_chart",
                },
                "退院指導情報収集":{
                    "chart_func":"count_task_chart",
                    "task_name":"退院指導情報収集",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Discharge_guidance_info_chart",
                },
                "注射台車鑑査":{
                    "chart_func":"count_task_chart",
                    "task_name":"注射台車鑑査",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Injection_cart_inspection_chart",
                },
                "無菌調製関連業務":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"無菌調製関連業務",
                    "chart_key":"Aseptic_preparation_chart",
                },
                "無菌調製(調製者)":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"無菌調製(調製者)",
                    "chart_key":"Aseptic_preparation_chart_for_preparer",
                },
                "無菌調製補助業務（準備、鑑査）":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"無菌調製補助業務（準備、鑑査）",
                    "chart_key":"Aseptic_preparation_chart_for_assistant",
                },
                "薬剤セット":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"薬剤セット",
                    "chart_key":"Medication_set_chart",
                },
                "薬剤セット確認":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"薬剤セット確認",
                    "chart_key":"Medication_set_check_chart",
                },
                "薬剤使用状況の把握等(情報収集)":{
                    "chart_func":"count_task_chart",
                    "task_name":"薬剤使用状況の把握等(情報収集)",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Medication_usage_info_chart",
                },
                "薬剤サマリー作成":{
                    "chart_func":"count_task_chart",
                    "task_name":"薬剤サマリー作成",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Medication_summary_chart",
                },
                "処方代理修正・代行入力":{
                    "chart_func":"count_task_chart",
                    "task_name":"処方代理修正・代行入力",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Prescription_proxy_chart",
                },
                "問い合わせ業務":{
                    "chart_func":"count_task_chart",
                    "task_name":"問い合わせ業務",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Inquiry_chart",
                },
                "ICT":{
                    "chart_func":"count_task_chart",
                    "task_name":"ICT",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"ICT_chart",
                },
                "AST":{
                    "chart_func":"count_task_chart",
                    "task_name":"AST",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"AST_chart",
                },
                "褥瘡":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"褥瘡",
                    "chart_key":"Jokusou_chart",
                },
                "手術後使用薬剤確認":{
                    "chart_func":"count_task_chart",
                    "task_name":"手術後使用薬剤確認",
                    "show_dataframe":True,
                    "chart":True,
                    "chart_key":"Postoperative_medication_chart",
                },
                "手術室サテライト薬剤定数確認":{
                    "chart_func":"simple_task_time_chart",
                    "task_name":"手術室サテライト薬剤定数確認",
                    "chart_key":"operroom_count_chart",
                },
                
            }